# Generated by Django 3.1.1 on 2020-09-28 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('user_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='balance.user')),
            ],
        ),
    ]
